"""Correlated virtual-population import for HumanSim.

The preferred route is to import complete individual rows generated by an established
population model such as httk-pop or PK-Sim, preserving physiological correlations.

This module does NOT generate independent Gaussian organ variables by default.
"""

from __future__ import annotations

import csv
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Mapping

import numpy as np

from research.human_sim.physiology import Physiology, TissueSpec


HTTK_MASS_FLOW_MAP = {
    "brain": ("Brain_mass", "Brain_flow"),
    "liver": ("Liver_mass", "Liver_flow"),
    "kidney": ("Kidneys_mass", "Kidneys_flow"),
}

PKSIM_EXPLICIT_TISSUES = {
    "brain": "Brain",
    "liver": "Liver",
    "kidney": "Kidney",
}
PKSIM_PERIPHERAL_TISSUES = (
    "Bone",
    "Fat",
    "Gonads",
    "Heart",
    "Muscle",
    "Pancreas",
    "Skin",
    "Spleen",
    "Stomach",
    "SmallIntestine",
    "LargeIntestine",
)

DEFAULT_TISSUE_DENSITY_KG_PER_L = {
    "brain": 1.04,
    "liver": 1.05,
    "kidney": 1.05,
    "blood": 1.06,
}


@dataclass(frozen=True)
class PopulationImportConfig:
    source_id: str = "httk_population"
    blood_density_kg_per_l: float = DEFAULT_TISSUE_DENSITY_KG_PER_L["blood"]
    tissue_density_kg_per_l: Mapping[str, float] | None = None

    def densities(self) -> dict[str, float]:
        values = dict(DEFAULT_TISSUE_DENSITY_KG_PER_L)
        if self.tissue_density_kg_per_l:
            values.update(self.tissue_density_kg_per_l)
        return values


@dataclass(frozen=True)
class VirtualIndividual:
    individual_id: str
    physiology: Physiology
    metadata: Mapping[str, str | float]
    source_id: str
    transforms: tuple[str, ...]

    def to_dict(self) -> dict:
        return {
            "individual_id": self.individual_id,
            "physiology": self.physiology.to_dict(),
            "metadata": dict(self.metadata),
            "source_id": self.source_id,
            "transforms": list(self.transforms),
        }


@dataclass(frozen=True)
class PopulationSummary:
    count: int
    central_volume_mean_l: float
    central_volume_sd_l: float
    tissue_volume_mean_l: Mapping[str, float]
    tissue_volume_sd_l: Mapping[str, float]
    tissue_flow_mean_l_per_h: Mapping[str, float]
    tissue_flow_sd_l_per_h: Mapping[str, float]

    def to_dict(self) -> dict:
        return asdict(self)


def _number(row: Mapping[str, str], name: str) -> float:
    raw = row.get(name)
    if raw is None or str(raw).strip() == "":
        raise ValueError(f"missing required population column {name}")
    value = float(raw)
    if not np.isfinite(value):
        raise ValueError(f"{name} must be finite")
    return value


def from_httkpop_row(
    row: Mapping[str, str],
    *,
    index: int,
    config: PopulationImportConfig = PopulationImportConfig(),
) -> VirtualIndividual:
    """Convert one httkpop_generate-style row to the reduced HumanSim body.

    httk-pop tissue masses are kg and tissue flows are L/h. The adapter converts
    masses to volumes with explicit density assumptions. All tissues not represented
    by the reduced HumanSim model are lumped into a peripheral compartment.

    This is a model-reduction transform, not a lossless import.
    """

    densities = config.densities()
    weight_column = "weight_adj" if str(row.get("weight_adj", "")).strip() else "weight"
    weight = _number(row, weight_column)
    blood_mass = _number(row, "Blood_mass")
    cardiac_output = _number(row, "CO")

    central_volume = blood_mass / config.blood_density_kg_per_l
    explicit_mass = 0.0
    explicit_flow = 0.0
    tissues = []

    for name, (mass_col, flow_col) in HTTK_MASS_FLOW_MAP.items():
        mass = _number(row, mass_col)
        flow = _number(row, flow_col)
        explicit_mass += mass
        explicit_flow += flow
        volume = mass / densities[name]
        tissues.append(TissueSpec(name, volume, flow))

    peripheral_mass = max(weight - blood_mass - explicit_mass, 1e-6)
    peripheral_flow = max(cardiac_output - explicit_flow, 0.0)
    tissues.append(TissueSpec("peripheral", peripheral_mass, peripheral_flow))

    physiology = Physiology(
        central_volume_l=central_volume,
        tissues=tuple(tissues),
        label=f"httkpop:{index}",
        evidence_status="source_backed_virtual_individual",
        source_ids=(config.source_id,),
    )
    physiology.validate()

    metadata = {}
    for name in ("gender", "reth", "age_years", "height", "weight", "weight_adj", "hematocrit"):
        if name in row and str(row[name]).strip() != "":
            try:
                metadata[name] = float(row[name])
            except ValueError:
                metadata[name] = str(row[name])

    return VirtualIndividual(
        individual_id=str(row.get("seqn") or f"row-{index}"),
        physiology=physiology,
        metadata=metadata,
        source_id=config.source_id,
        transforms=(
            "Blood_mass / blood_density -> central_volume_l",
            "Brain/Liver/Kidneys mass / explicit density -> tissue volume",
            "Residual body mass -> peripheral volume at 1 kg/L",
            "Residual cardiac output -> peripheral flow",
        ),
    )


def load_httkpop_csv(
    path: str | Path,
    *,
    config: PopulationImportConfig = PopulationImportConfig(),
) -> list[VirtualIndividual]:
    rows = _read_csv_rows(path)
    return [
        from_httkpop_row(row, index=index, config=config)
        for index, row in enumerate(rows)
    ]



def _pksim_column(row: Mapping[str, str], path: str, unit: str) -> str:
    candidates = (f"{path} [{unit}]", path)
    for candidate in candidates:
        if candidate in row and str(row[candidate]).strip() != "":
            return candidate
    raise ValueError(f"missing required PK-Sim column {path}")


def _pksim_volume(row: Mapping[str, str], organ: str) -> float:
    return _number(row, _pksim_column(row, f"Organism|{organ}|Volume", "l"))


def _pksim_specific_flow(row: Mapping[str, str], organ: str) -> float:
    return _number(
        row,
        _pksim_column(
            row,
            f"Organism|{organ}|Specific blood flow rate",
            "l/min/kg organ",
        ),
    )


def _pksim_total_flow_l_per_h(
    row: Mapping[str, str],
    organ: str,
    density_kg_per_l: float,
) -> float:
    volume = _pksim_volume(row, organ)
    specific = _pksim_specific_flow(row, organ)
    return specific * volume * density_kg_per_l * 60.0


def from_pksim_row(
    row: Mapping[str, str],
    *,
    index: int,
    config: PopulationImportConfig = PopulationImportConfig(source_id="pksim_population"),
) -> VirtualIndividual:
    """Convert a PK-Sim population-export row to the reduced HumanSim body.

    PK-Sim provides organ volumes directly. Blood flow is exported as a specific
    flow rate (L/min/kg organ), so total organ flow requires an explicit tissue-density
    conversion. Systemic tissues not represented explicitly are lumped into peripheral.

    Lung is intentionally excluded from the parallel peripheral lump because pulmonary
    flow is not a parallel systemic organ flow in this reduced topology.
    """

    densities = config.densities()
    venous = _number(row, _pksim_column(row, "Organism|VenousBlood|Volume", "l"))
    arterial = _number(row, _pksim_column(row, "Organism|ArterialBlood|Volume", "l"))
    central_volume = venous + arterial

    tissues = []
    for name, organ in PKSIM_EXPLICIT_TISSUES.items():
        volume = _pksim_volume(row, organ)
        density = densities.get(name, 1.0)
        flow = _pksim_total_flow_l_per_h(row, organ, density)
        tissues.append(TissueSpec(name, volume, flow))

    peripheral_volume = 0.0
    peripheral_flow = 0.0
    for organ in PKSIM_PERIPHERAL_TISSUES:
        try:
            volume = _pksim_volume(row, organ)
            flow = _pksim_total_flow_l_per_h(row, organ, 1.0)
        except ValueError:
            continue
        peripheral_volume += volume
        peripheral_flow += flow

    if peripheral_volume <= 0:
        raise ValueError("PK-Sim row contains no usable peripheral tissue volumes")
    tissues.append(TissueSpec("peripheral", peripheral_volume, peripheral_flow))

    physiology = Physiology(
        central_volume_l=central_volume,
        tissues=tuple(tissues),
        label=f"pksim:{row.get('IndividualId', index)}",
        evidence_status="source_backed_virtual_individual",
        source_ids=(config.source_id,),
    )
    physiology.validate()

    metadata = {}
    for key in ("IndividualId", "Gender", "Population", "Population Name"):
        if key in row and str(row[key]).strip() != "":
            metadata[key] = str(row[key])
    for path in ("Organism|Age", "Organism|Weight", "Organism|Hematocrit"):
        for key in row:
            if key == path or key.startswith(path + " ["):
                if str(row[key]).strip() != "":
                    metadata[path] = float(row[key])
                break

    return VirtualIndividual(
        individual_id=str(row.get("IndividualId") or f"row-{index}"),
        physiology=physiology,
        metadata=metadata,
        source_id=config.source_id,
        transforms=(
            "VenousBlood volume + ArterialBlood volume -> central_volume_l",
            "PK-Sim organ Volume -> tissue volume directly",
            "Specific blood flow * organ volume * density * 60 -> L/h",
            "Selected systemic tissue volumes/flows -> peripheral lump",
            "Pulmonary compartment excluded from parallel systemic lump",
        ),
    )


def _read_csv_rows(path: str | Path) -> list[dict[str, str]]:
    path = Path(path)
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        lines = [line for line in handle if not line.lstrip().startswith("#")]
    rows = list(csv.DictReader(lines))
    if not rows:
        raise ValueError("population CSV contains no rows")
    return rows


def load_pksim_csv(
    path: str | Path,
    *,
    config: PopulationImportConfig = PopulationImportConfig(source_id="pksim_population"),
) -> list[VirtualIndividual]:
    rows = _read_csv_rows(path)
    return [
        from_pksim_row(row, index=index, config=config)
        for index, row in enumerate(rows)
    ]


def detect_population_format(path: str | Path) -> str:
    rows = _read_csv_rows(path)
    columns = set(rows[0])
    if "Blood_mass" in columns and "Brain_mass" in columns:
        return "httk"
    if any(col.startswith("Organism|Brain|Volume") for col in columns):
        return "pksim"
    raise ValueError("could not detect population CSV format")


def load_population_csv(
    path: str | Path,
    *,
    format: str = "auto",
) -> list[VirtualIndividual]:
    selected = detect_population_format(path) if format == "auto" else format.lower()
    if selected == "httk":
        return load_httkpop_csv(path)
    if selected == "pksim":
        return load_pksim_csv(path)
    raise ValueError("format must be one of: auto, httk, pksim")


def summarize_population(individuals: Iterable[VirtualIndividual]) -> PopulationSummary:
    members = list(individuals)
    if not members:
        raise ValueError("population cannot be empty")

    tissue_names = set(members[0].physiology.tissue_map)
    if any(set(member.physiology.tissue_map) != tissue_names for member in members):
        raise ValueError("population members must share the same reduced tissue schema")

    central = np.array([member.physiology.central_volume_l for member in members])
    volume = {
        name: np.array([member.physiology.tissue_map[name].volume_l for member in members])
        for name in tissue_names
    }
    flow = {
        name: np.array([
            member.physiology.tissue_map[name].blood_flow_l_per_h for member in members
        ])
        for name in tissue_names
    }

    return PopulationSummary(
        count=len(members),
        central_volume_mean_l=float(np.mean(central)),
        central_volume_sd_l=float(np.std(central, ddof=1)) if len(members) > 1 else 0.0,
        tissue_volume_mean_l={name: float(np.mean(values)) for name, values in volume.items()},
        tissue_volume_sd_l={
            name: float(np.std(values, ddof=1)) if len(members) > 1 else 0.0
            for name, values in volume.items()
        },
        tissue_flow_mean_l_per_h={name: float(np.mean(values)) for name, values in flow.items()},
        tissue_flow_sd_l_per_h={
            name: float(np.std(values, ddof=1)) if len(members) > 1 else 0.0
            for name, values in flow.items()
        },
    )
