            'Azidomorphine': ['40x potency of Morphine with high affinity to μ...'],
            'Myrophine': ['Morphine + 3-benzyl & 6-myristyl chain and acts as...'],
            'Dipropanoylmorphine': ['Ester of M used to treat severe pain. Rarely used ...'],
            'Methyldihydromorphine': ['Related to heterocodeine not dihydrocodeine. Could...'],
            'Diacetyldihydromorphine': ['Occasionally used an alternative to diamorphine, o...'],
            'Heterocodeine': ['Reverse isomer of codeine. 6x potency of M, while ...'],
            'Methyldesorphin': ['15x potency of M. Is found in Krokodil...'],
            'Oxymorphazone': ['half potency as OM but higher doses last up to 48h...'],
            'Chloroxymorphamine': ['Derivative of OM and irreversible full agonist...'],
            'Nicomorphine': ['2-3x the potency of M and commonly prescribed in G...'],
            'Metopon': ['Methylated Hydromorphone, less potent. Interesting...'],
            'Tapentadol': ['μ & σ agonist & SNRI. Potency in between M & Tram....'],
            'Ciramadol': ['Opioid related to PCP, Tramadol & Tapentadol. mixe...'],
            'Oxymorphol': ['6-hydrogenated OM, coming soon......'],
            'Pentamorphone': ['few x stronger than fent. short duration but low r...'],
            'Hydromorphinol': ['Derivative of M but more potent, with a steeper do...'],
            'Carfentanil': ['100x potency of fent., 10000x the potency of M. Us...'],
            'Lofentanil': ['more potent and with a longer duration than carfen...'],
            'Remifentanil': ['Potent ultra short acting fent. analogue. Potency ...'],
            'Ohmefentanyl': ['6300x morphine at it\'s most active isomer. Analog...'],
            'Alfentanil': ['1/4 the potency and 1/3 the duration of fent but 4...'],
            'Betahydroxythiofentanyl': ['one of the more favoured fent. analogues by addict...'],
            'Sufentanil': ['5-10x potency of fent....'],
            'Mirfentanil': ['fent. analogue with strong selevtivity over μ. Low...'],
            'Etorphine': ['1000-3000x potency of M. μ, κ & δ opioid agonist. ...'],
            'Acetorphine': ['8700x potency of M...'],
            'Etonitazene': ['1000-1500x potency of M....'],
            'Bromadol (BDPC)': ['500-10,000x potency of M. Similar to PCP analogues...'],
            'Ketobemidone': ['μ opioid antagonist & NMDA antagonist. More addict...'],
            'Acetoxyketobemidone': ['Unschedualed analogue of ketobemidone...'],
            'Bemidone': ['Analogue of Pethidine but significantly less poten...'],
            'Dipipadone': ['Lost Ark of the Covenant....'],
            'Phenadoxone': ['methadone analogue, similar dose to M, lasts 1-4 h...'],
            'Levacetylmethadol': ['Methadone analogue with u agonism and noncompetiti...'],
            'Dimenoxadol': ['Benzillic Acid derivative related to methadone. Ba...'],
            'Dimepheptadol': ['related to methadone, has two isomers which also h...'],
            'Dioxaphetyl butyrate': ['Banned opioid similar to methadone. Possibly in us...'],
            'Lefetamine': ['Weak opiate on the same scale as codeine but has D...'],
            'Norpipanone': ['Was not under international control until case rep...'],
            'Piminodine': ['similar dose to M, used in 60\'s and 70\'s but was...'],
            'Anileridine': ['Another banned pethidine analogue, probably abused...'],
            'Benzethidine': ['4-phenylpiperidine analogue of pethidine. Probably...'],
            'Furethidine': ['4-Phenylpiperidine analogue of pethidine. Probably...'],
            'Carperidine': ['fairly normal opiate but unused in medicine and cu...'],
            'Morpheridine': ['related to meperidine but 4x the potency and does ...'],
            'Phenoperidine': ['20-200x the potency of Pethidine. Less hypnotic an...'],
            'Picenadol': ['R isomer (or Levopicenadol) is pure μ agonist whil...'],
            'Allylprodine': ['Prodine analogue 23x potency of M...'],
            'Prosidol': ['Russian Prodine analogue...'],
            'Palfium (Dextomoramide)': ['3x potency of M but shorter acting. High BA & fast...'],
            'Propiram': ['Slightly more potent than codeine, 3-6hr duration....'],
            'Diampromide': ['Banned Analgesic related to Propiram. Similar pote...'],
            'Herkinorin': ['Analogue of Salvinorin A but the complete opposite...'],
            'Methopholine': ['Isoquinilone derivative with same efficacy as code...'],
            'Nortilidine': ['Equipotency of M. Opioid activity is in (1S,2R) is...'],
            ''Synthetic Conotoxin'': ['Snail toxin derived painkiller 1000x potency of mo...'],
            'Loperamide': ['Peripheral opioid so it cannot cross BBB. useful a...'],
            'Bezitramide': ['(Burgodin?)...'],
            'Piritramide': ['0.65-0.75x M but still effect is strong and long l...'],
            'Thiambutenes': ['Dimethyl-TAB, Diethyl-TAB, Ethylmethyl-TAB. Used i...'],
            'Dextropropoxyphene': ['Low potency opiate not absorbed by CYP2D6. Also is...'],
            'Deltorphin': ['High affinity and selectivity, naturally occuring ...'],
            'Dermorphin': ['South American Tree frog skin. Natural opioid pept...'],
            'Thebaine': ['6, 14 dimethoxy version of OM. Stimulant rather th...'],
            'Thebacon': ['Thebaine analogue and fairly uninteresting...'],
            'Drotebanol': ['Morphinan derivative synthesised from Thebaine wit...'],
            'Biphalin': ['endogenous eptide with high affinity for δ & μ rec...'],
            'Opiorphin': ['Endogenous opioid isolated from human saliva....'],
            'Casomorphins': ['opiates found in Cow\'s milk....'],
            'Eseroline': ['Metabolite of the ACh inhibitor physostigmine but ...'],
            'Hodgkinsine': ['alkaloid found in Psychotria colorata plants. Has ...'],
            'Mitragynine': ['Alkaloid in Kratom. Fairly selective μ agonist but...'],
            'Butinazocine': ['benzomorphan opioid that was never marketed-------...'],
            'Carbazocine': ['benzomorphan opioid that was never marketed 		    ...'],
            'Etazocine': ['partial opioid agonist with mixed ant.-ag. effects...'],
            'Ethylketocyclozocine': ['partial opioid agonist with mixed ant.-ag. effects...'],
            'Ibazocine': ['benzomorphan opioid that was never marketed			    ...'],
            'Moxazocine': ['10x potency of M, partial/mixed ant.-ag.			      _...'],
            'Tonazocine': ['partial agonist at μ & δ, no adverse effects on br...'],
            'Volazocine': ['benzomorphan opioid that was never marketed		    /...'],
            'Fluorophen': ['radioligand, full μ agonist (6x M) & lower affinit...'],
            'Zenazocine': ['partial agonist at μ & δ--------------------------...'],
            'Phenomorphan': ['OPIATE...'],
            'Proxorphan': ['OPIATE...'],
            'Levophenacylmorphan': ['OPIATE...'],
            'Levomethorphan (+)': ['NDMA antagonist, σ1 & σ2 sigma agonist, μ, δ & κ o...'],
            'Levorphanol (+)': ['μ, κ & δ agonist, 4-8x potency of M, long duration...'],
            'Norlevorphanol': ['Opioid analgesic, uninteresting....'],
            'Chlornaltrexamine': ['Irreversible mixed ant.-ag. at μ opioid. 22x more ...'],
            'Naloxazone': ['Irreversible μ opioid receptor antagonist...'],
            'Naloxonazine': ['Very Potent Irreversible μ opioid antagonist. dime...'],
            'Buprenorphin': ['Subutex...'],
            'Levallorphan': ['μ opioid antagonist, when used with opiate, it pot...'],
            'Diprenorphine': ['Strongest opiate antagonist available. 100x potenc...'],
            'Cyprodime': ['ANTI-OPIOID...'],
            'Xorphanol': ['ANTI-OPIOID...'],
            'Samidorphan': ['ANTI-OPIOID...'],
            'Butorphanol': ['HALLUCINOGENIC OPIATE...'],
            'Eptazocine': ['Japanese κ agonist & μ antagonist...'],
            'Amiphenazole': ['treatment for OD. counteracts respiratory depressi...'],
            'Naltrexone': ['Competitive antagonist at μ & κ receptors, and to ...'],
            'Nalbuphine': ['mixed ant.-ag. as is common with this class, there...'],
            'Cyclorphan': ['HALLUCINOGENIC OPIATE...'],
            'Pentazocine': ['mixed ant.-ag. (-) is the κ agonist side, the (+) ...'],
            'Phenazocine': ['related to ^ but stronger analgesic, 4x potency of...'],
            'Cyclazocine': ['mixed ant.-ag....'],
            'Dezocine': ['Mixed ant.-ag. with high κ antagonism. Low dose=eu...'],
            'Bremazocine': ['κ agonist related to Pentazocine...'],
            'Metazocine': ['analgesic; mixed ant.-ag. at μ, activity also at κ...'],
            'Cyprenorphine': ['Buprenorphine analogue, ant.-ag. effects but with ...'],
            'Ibogaine': ['Addiction CURE. HT2a agonist, κ opioid agonist, NM...'],
            'Noribogaine': ['Metabolite of Ibogaine. Potent SRI, κ antagonist, ...'],
            'Voacangine': ['precursor to Ibogine used by iboga plant. Displays...'],
            'Salvinorin A': ['Highly potent κ agonist and even more potent D2 pa...'],
            'Salvinorin B ethoxymethyl ether': ['semi-synthetic analogue of Salv. A. Longer duratio...'],
            'Salvinorin B methoxymethyl ether': ['Similar to ^^ but less selective. 5x potency as Sa...'],
            'Enadoline': ['Highly selective κ agonist. Produces visual distor...'],
            'Tifluradom': ['Benzo derivative but without GABAa agonism. Instea...'],
            'Alazocine': ['σ1 agonist, κ opioid agonist & slight NMDA antagon...'],
            'Oxilorphan': ['HALLUCINOGENIC OPIATE...'],
            'Dimemorfan': ['SIGMAERGIC DRUG...'],
            'Chitosan': ['linear polysaccharide that can give Morphine up to...'],
            'NMDA antagonists': ['Inhibit development of tolerance to morphine...'],
            'Tezampanel': ['ANXIOLYTIC...'],
            'Ibudilast': ['NOOTROPIC...'],
            'Tetrahydropalmatine': ['ANXIOLYTIC...'],
            'Lofexidine': ['ANXIOLYTIC...'],
            'd & l Phenylalanine (DLPA)': ['Increases dopamine and endorphin levels, reducing ...'],
            'Proglumide': ['Acts as a d opioid agonist and non selective CCK a...'],
            'Devazepide': ['No affinity for GABAa, selective CCKa antagonist....'],
            'Lorglumide': ['Selective CCKa antagonist for treatment of gastroi...'],
            'Menabitan': ['potent cannabinoid receptor agonist with anti-noci...'],
            'Diphenhydramine': ['Removes Nausea effectively, slight potentiation at...'],
            'Dimenhydrinate': ['Similar to DPH, more effective against nausea...'],
            'Promethazine': ['1st Gen. Antihistamine with low hall. dose : effec...'],
            'Hydroxyzine': ['Also HT2a and D2 antagonist....'],
            'Cyclizine': ['Strong potentiation...'],
            'Chlorphenamine': ['SNRI, potentiation present but minimal....'],
            'Tripelennamine': ['weak SDRI with minimal anti-cholinergic effects....'],
            'Orphenadrine': ['NMDA antagonist...'],
            'Imipramine': ['Triple RI, D releaser, ACh M2 antagonist, adrenerg...'],
            'Ciproxifan': ['potent H3 inverse agonist/antagonist, wakefulness ...'],
            'Cyproheptadine': ['Very non-selective antihistamine. Antag. at H1(.06...'],
            'Dimetotiazine': ['Japanese Antihistamine and ?serotonin? antagonist....'],
            'Cipralisant': ['extremely potent H3 agonist, S-isomer is active on...'],
            'Imetit': ['h3 agonist...'],
            'Immethridine': ['H3 agonist...'],
            'Methimepip': ['H3 agonist...'],
            'Proxyfan': ['h3 agonist but is \"protean agonist\". It gives di...'],
            'Huperzine A': ['acetylcholinesterase inhibitor, NMDA antagonist...'],
            'Tacrine': ['anticholinesterase & cholinergic agonist. also a h...'],
            'Bifemelane': ['Cholinergic nootropic...'],
            'Galantamine': ['reversable cholinesterase inhibitor, Nico. choline...'],
            'Arecoline': ['Areca nut alkaloid. Muscarinic ACh partial agonist...'],
            'Diphenylpyraline': ['anti-cholinergic, anti-histamine DRI...'],
            'Donepezil': ['reversble acetylcholinesterase inhibitor, 100% BA...'],
            'Physostigmine': ['reversible cholinesterase inhibitor. Indirectly st...'],
            'Indeloxazine': ['S releaser, DRI, NMDA antag., acetylcholine releas...'],
            'Ispronicline': ['Nico. ACh partial agonist, α4β2 subtype selective...'],
            'Muscarine': ['Along with Muscarinic Acid, active alkaloids found...'],
