"""Longitudinal competing-null benchmark on synthetic observable panels.

This module asks a harder question than parameter recovery:

    Do receptor-labelled mechanism covariates improve held-out prediction beyond
    history, stress/arousal and sleep/wake-context null models?

It also runs the reverse falsification check. When data are generated by a context-only
truth, the receptor model MUST NOT systematically win.

Everything is synthetic. Mechanism inputs are dimensionless labels from the toy model,
not doses or suggested human exposures. "EEG" and wearable outcomes are the synthetic
proxy channels defined in observable_model.py, not validated biomarkers.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, Mapping, Sequence

import numpy as np

from research.dissociation.experimental_design import build_candidate_library
from research.dissociation.model import MechanismInput, ModelParameters, PopulationConfig, simulate
from research.dissociation.observable_model import (
    ALL_CHANNELS, MeasurementConfig, expected_observables,
)


CONTEXT_FEATURES = (
    "stress_load",
    "sleep_wake_irregularity",
    "social_conflict_load",
    "time_trend",
)
HISTORY_FEATURES = (
    "lag_observer_switch_rate",
    "lag_paired_recall_success",
)
MECHANISM_FEATURES = (
    "meth",
    "nmda_antagonism",
    "mor_partial_agonism",
    "kor_antagonism",
    "wake_anchor_disruption",
)

MODEL_FEATURES: dict[str, tuple[str, ...]] = {
    "mean_only": (),
    "history_only": HISTORY_FEATURES,
    "context_only": CONTEXT_FEATURES,
    "context_history": CONTEXT_FEATURES + HISTORY_FEATURES,
    "mechanism_only": MECHANISM_FEATURES,
    "context_plus_mechanism": CONTEXT_FEATURES + MECHANISM_FEATURES,
    "full": CONTEXT_FEATURES + HISTORY_FEATURES + MECHANISM_FEATURES,
}


@dataclass(frozen=True)
class LongitudinalConfig:
    subjects: int = 6
    sessions: int = 24
    micro_population: int = 90
    steps_per_session: int = 28
    seed: int = 140
    test_fraction: float = 0.25
    receptor_weight_mixed: float = 0.60
    ridge: float = 1e-3

    def validate(self) -> None:
        if self.subjects < 2:
            raise ValueError("subjects must be >= 2")
        if self.sessions < 8:
            raise ValueError("sessions must be >= 8")
        if self.micro_population < 10 or self.steps_per_session < 5:
            raise ValueError("simulation population/steps too small")
        if not 0.1 <= self.test_fraction <= 0.5:
            raise ValueError("test_fraction must be in [0.1, 0.5]")
        if not 0.0 <= self.receptor_weight_mixed <= 1.0:
            raise ValueError("receptor_weight_mixed must be in [0,1]")
        if self.ridge < 0:
            raise ValueError("ridge must be non-negative")


@dataclass
class ModelScore:
    model: str
    parameters: int
    observed_test_values: int
    test_mse: float
    test_rmse: float
    test_r2: float
    train_bic: float

    def to_dict(self) -> dict:
        return asdict(self)


def _unit(x: float) -> float:
    return float(np.clip(x, 0.0, 1.0))


def _condition_seed(name: str) -> int:
    digest = hashlib.blake2b(name.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "little")


def _condition_cycle() -> list[tuple[str, MechanismInput]]:
    library = build_candidate_library()
    # Use varied single and combination conditions. Sorting keeps reproducibility
    # independent of dict construction.
    return sorted(library.items(), key=lambda item: item[0])


def _context_means(row: Mapping[str, float]) -> dict[str, float]:
    """Non-receptor alternative generator.

    It deliberately explains the same *kinds* of observable outcomes through generic
    stress, schedule disruption, conflict load and autoregressive persistence.
    """
    stress = row["stress_load"]
    wake = row["sleep_wake_irregularity"]
    conflict = row["social_conflict_load"]
    lag_switch = row["lag_observer_switch_rate"]
    lag_recall = row["lag_paired_recall_success"]

    return {
        "observer_switch_rate": _unit(
            0.035 + 0.24 * stress + 0.17 * wake + 0.10 * conflict + 0.28 * lag_switch
        ),
        "paired_recall_success": _unit(
            0.88 - 0.20 * stress - 0.23 * wake - 0.10 * conflict + 0.20 * lag_recall
        ),
        "morning_plan_agreement": _unit(
            0.86 - 0.13 * stress - 0.34 * wake - 0.14 * conflict
        ),
        "wearable_arousal_index": (
            -0.22 + 0.78 * stress + 0.28 * conflict + 0.16 * wake
        ),
        "eeg_connectivity_index": (
            0.35 - 0.25 * stress - 0.36 * wake - 0.08 * conflict
        ),
    }


def _sample_from_means(
    means: Mapping[str, float],
    rng: np.random.Generator,
    measurement: MeasurementConfig,
) -> dict[str, float]:
    measurement.validate()
    result = {
        "observer_switch_rate": rng.binomial(
            measurement.switch_checks, _unit(means["observer_switch_rate"])
        ) / measurement.switch_checks,
        "paired_recall_success": rng.binomial(
            measurement.recall_trials, _unit(means["paired_recall_success"])
        ) / measurement.recall_trials,
        "morning_plan_agreement": rng.binomial(
            measurement.plan_trials, _unit(means["morning_plan_agreement"])
        ) / measurement.plan_trials,
        "wearable_arousal_index": rng.normal(
            means["wearable_arousal_index"], measurement.wearable_noise_sd
        ),
        "eeg_connectivity_index": rng.normal(
            means["eeg_connectivity_index"], measurement.eeg_noise_sd
        ),
    }
    for channel in ALL_CHANNELS:
        if rng.random() < measurement.missing_probability:
            result[channel] = float("nan")
    return result


def generate_panel(
    truth: str,
    *,
    config: LongitudinalConfig = LongitudinalConfig(),
    measurement: MeasurementConfig = MeasurementConfig(),
    params: ModelParameters = ModelParameters(),
) -> list[dict]:
    """Generate session-level longitudinal observations.

    truth:
      receptor  -> toy receptor/state model + measurement process
      context   -> stress/wake/history null generator
      mixed     -> convex combination before observation noise

    Non-pharmacological context is mildly correlated with some mechanism labels to
    make the comparison non-trivial and expose confounding.
    """
    config.validate()
    measurement.validate()
    if truth not in {"receptor", "context", "mixed"}:
        raise ValueError("truth must be receptor, context, or mixed")

    conditions = _condition_cycle()
    rows: list[dict] = []

    for subject in range(config.subjects):
        rng = np.random.default_rng(config.seed + 1009 * subject)
        subject_offsets = {
            "observer_switch_rate": rng.normal(0.0, 0.018),
            "paired_recall_success": rng.normal(0.0, 0.025),
            "morning_plan_agreement": rng.normal(0.0, 0.030),
            "wearable_arousal_index": rng.normal(0.0, 0.080),
            "eeg_connectivity_index": rng.normal(0.0, 0.070),
        }
        lag_switch = 0.08
        lag_recall = 0.78

        # Subject-specific cyclic offset prevents every person seeing conditions
        # in exactly the same temporal order.
        cycle_offset = (subject * 5) % len(conditions)
        for session in range(config.sessions):
            name, mechanism = conditions[(session + cycle_offset) % len(conditions)]
            # Context terms intentionally share variance with some mechanism labels.
            stress = _unit(
                rng.beta(2.0, 3.0)
                + 0.12 * mechanism.meth
                + 0.06 * mechanism.nmda_antagonism
            )
            sleep_wake = _unit(
                rng.beta(1.8, 3.2)
                + 0.24 * mechanism.wake_anchor_disruption
                + 0.07 * mechanism.meth
            )
            conflict = _unit(
                rng.beta(1.5, 4.0)
                + 0.08 * mechanism.meth
            )
            time_trend = session / max(1, config.sessions - 1)

            covariates = {
                "stress_load": stress,
                "sleep_wake_irregularity": sleep_wake,
                "social_conflict_load": conflict,
                "time_trend": time_trend,
                "lag_observer_switch_rate": lag_switch,
                "lag_paired_recall_success": lag_recall,
                **{
                    key: float(getattr(mechanism, key))
                    for key in MECHANISM_FEATURES
                },
            }

            # Same subject baseline across conditions, but a condition-keyed offset
            # makes repeated runs reproducible.
            pop_seed = (
                config.seed
                + 5003 * subject
                + (_condition_seed(name) % 100000)
            )
            summary = simulate(
                mechanism,
                config=PopulationConfig(
                    n_subjects=config.micro_population,
                    steps=config.steps_per_session,
                    seed=pop_seed,
                ),
                params=params,
            )
            receptor_means = expected_observables(summary, measurement)
            context_means = _context_means(covariates)

            if truth == "receptor":
                means = receptor_means
            elif truth == "context":
                means = context_means
            else:
                w = config.receptor_weight_mixed
                means = {
                    channel: w * receptor_means[channel] + (1.0 - w) * context_means[channel]
                    for channel in ALL_CHANNELS
                }

            means = {
                channel: value + subject_offsets[channel]
                for channel, value in means.items()
            }

            obs_seed = np.random.SeedSequence([
                config.seed,
                subject,
                session,
                int(_condition_seed(name) & 0xffffffff),
            ])
            observed = _sample_from_means(
                means, np.random.default_rng(obs_seed), measurement
            )

            row = {
                "subject": subject,
                "session": session,
                "condition": name,
                **covariates,
                **observed,
            }
            rows.append(row)

            # History covariates are based on the last available report, otherwise
            # retained from the previous session.
            if np.isfinite(observed["observer_switch_rate"]):
                lag_switch = float(observed["observer_switch_rate"])
            if np.isfinite(observed["paired_recall_success"]):
                lag_recall = float(observed["paired_recall_success"])

    return rows


def _train_test_masks(rows: Sequence[dict], test_fraction: float) -> tuple[np.ndarray, np.ndarray]:
    train = np.zeros(len(rows), dtype=bool)
    test = np.zeros(len(rows), dtype=bool)
    by_subject: dict[int, list[int]] = {}
    for idx, row in enumerate(rows):
        by_subject.setdefault(int(row["subject"]), []).append(idx)
    for indices in by_subject.values():
        indices.sort(key=lambda idx: int(rows[idx]["session"]))
        n_test = max(1, int(round(len(indices) * test_fraction)))
        test[indices[-n_test:]] = True
        train[indices[:-n_test]] = True
    return train, test


def _design_matrix(
    rows: Sequence[dict],
    features: Sequence[str],
    *,
    train_mask: np.ndarray,
) -> tuple[np.ndarray, int]:
    # Intercept + subject fixed effects + requested features.
    subjects = sorted({int(row["subject"]) for row in rows})
    subject_reference = subjects[0]
    subject_columns = [s for s in subjects if s != subject_reference]

    feature_matrix = np.array([
        [float(row[name]) for name in features]
        for row in rows
    ], dtype=float) if features else np.zeros((len(rows), 0), dtype=float)

    if features:
        mu = np.mean(feature_matrix[train_mask], axis=0)
        sd = np.std(feature_matrix[train_mask], axis=0)
        sd = np.where(sd < 1e-9, 1.0, sd)
        feature_matrix = (feature_matrix - mu) / sd

    subject_matrix = np.array([
        [1.0 if int(row["subject"]) == subject else 0.0 for subject in subject_columns]
        for row in rows
    ], dtype=float)
    x = np.concatenate([
        np.ones((len(rows), 1), dtype=float),
        subject_matrix,
        feature_matrix,
    ], axis=1)
    return x, x.shape[1]


def _fit_channel(
    x: np.ndarray,
    y: np.ndarray,
    train_mask: np.ndarray,
    test_mask: np.ndarray,
    ridge: float,
) -> tuple[np.ndarray, np.ndarray, int, float]:
    valid_train = train_mask & np.isfinite(y)
    valid_test = test_mask & np.isfinite(y)
    if np.sum(valid_train) <= x.shape[1] or not np.any(valid_test):
        return np.array([]), np.array([]), 0, float("nan")

    xtx = x[valid_train].T @ x[valid_train]
    penalty = ridge * np.eye(xtx.shape[0])
    penalty[0, 0] = 0.0
    beta = np.linalg.solve(
        xtx + penalty,
        x[valid_train].T @ y[valid_train],
    )
    train_pred = x[valid_train] @ beta
    test_pred = x[valid_test] @ beta
    return train_pred, test_pred, int(len(beta)), float(np.sum(valid_train))


def score_models(
    rows: Sequence[dict],
    *,
    config: LongitudinalConfig,
) -> list[ModelScore]:
    train_mask, test_mask = _train_test_masks(rows, config.test_fraction)
    scores = []

    for model_name, features in MODEL_FEATURES.items():
        x, _ = _design_matrix(rows, features, train_mask=train_mask)

        train_sse = 0.0
        train_n = 0
        test_sse = 0.0
        test_n = 0
        test_values = []
        test_predictions = []
        parameters = 0

        for channel in ALL_CHANNELS:
            y = np.array([row[channel] for row in rows], dtype=float)
            valid_train = train_mask & np.isfinite(y)
            valid_test = test_mask & np.isfinite(y)
            train_pred, test_pred, k, _ = _fit_channel(
                x, y, train_mask, test_mask, config.ridge
            )
            if k == 0:
                continue
            parameters += k
            train_y = y[valid_train]
            test_y = y[valid_test]
            train_sse += float(np.sum((train_y - train_pred) ** 2))
            train_n += len(train_y)
            test_sse += float(np.sum((test_y - test_pred) ** 2))
            test_n += len(test_y)
            test_values.extend(test_y.tolist())
            test_predictions.extend(test_pred.tolist())

        if test_n == 0 or train_n == 0:
            test_mse = float("inf")
            test_rmse = float("inf")
            r2 = float("-inf")
            bic = float("inf")
        else:
            test_mse = test_sse / test_n
            test_rmse = float(np.sqrt(test_mse))
            y_test = np.asarray(test_values)
            pred_test = np.asarray(test_predictions)
            ss_total = float(np.sum((y_test - np.mean(y_test)) ** 2))
            r2 = 1.0 - test_sse / ss_total if ss_total > 1e-12 else 0.0
            train_sse_safe = max(train_sse, 1e-12)
            bic = float(
                train_n * np.log(train_sse_safe / train_n)
                + parameters * np.log(train_n)
            )

        scores.append(ModelScore(
            model=model_name,
            parameters=parameters,
            observed_test_values=test_n,
            test_mse=test_mse,
            test_rmse=test_rmse,
            test_r2=r2,
            train_bic=bic,
        ))
    return sorted(scores, key=lambda score: score.test_mse)


def permute_mechanisms_within_subject(rows: Sequence[dict], seed: int) -> list[dict]:
    """Negative control: destroy mechanism/outcome alignment, preserve context/history."""
    result = [dict(row) for row in rows]
    rng = np.random.default_rng(seed)
    by_subject: dict[int, list[int]] = {}
    for idx, row in enumerate(result):
        by_subject.setdefault(int(row["subject"]), []).append(idx)
    for indices in by_subject.values():
        values = np.array([
            [result[idx][name] for name in MECHANISM_FEATURES]
            for idx in indices
        ], dtype=float)
        rng.shuffle(values, axis=0)
        for idx, vector in zip(indices, values):
            for name, value in zip(MECHANISM_FEATURES, vector):
                result[idx][name] = float(value)
    return result


def _score_map(scores: Sequence[ModelScore]) -> dict[str, ModelScore]:
    return {score.model: score for score in scores}


def discrimination_diagnostics(
    original: Sequence[ModelScore],
    permuted: Sequence[ModelScore],
) -> dict[str, float | str]:
    """Quantify model-family separation instead of relying on rank alone."""
    orig = _score_map(original)
    perm = _score_map(permuted)

    null_names = [
        name for name in ("mean_only", "history_only", "context_only", "context_history")
        if name in orig
    ]
    mechanism_names = [
        name for name in ("mechanism_only", "context_plus_mechanism", "full")
        if name in orig
    ]
    if not null_names or not mechanism_names:
        return {"status": "insufficient_model_families"}

    best_null = min(null_names, key=lambda name: orig[name].test_mse)
    best_mechanism = min(mechanism_names, key=lambda name: orig[name].test_mse)
    best_mechanism_permuted = min(
        mechanism_names, key=lambda name: perm[name].test_mse
    )

    null_mse = orig[best_null].test_mse
    mech_mse = orig[best_mechanism].test_mse
    perm_mse = perm[best_mechanism_permuted].test_mse
    return {
        "status": "ok",
        "best_null_model": best_null,
        "best_mechanism_model": best_mechanism,
        "best_permuted_mechanism_model": best_mechanism_permuted,
        "best_null_mse": null_mse,
        "best_mechanism_mse": mech_mse,
        "mechanism_gain_over_null_fraction": (
            (null_mse - mech_mse) / max(null_mse, 1e-12)
        ),
        "mechanism_permutation_penalty_fraction": (
            (perm_mse - mech_mse) / max(mech_mse, 1e-12)
        ),
    }


def benchmark_truth(
    truth: str,
    *,
    config: LongitudinalConfig,
    measurement: MeasurementConfig,
) -> dict:
    rows = generate_panel(truth, config=config, measurement=measurement)
    original = score_models(rows, config=config)
    permuted = score_models(
        permute_mechanisms_within_subject(rows, config.seed + 901),
        config=config,
    )
    return {
        "truth": truth,
        "rows": len(rows),
        "scores": [score.to_dict() for score in original],
        "permuted_mechanism_scores": [score.to_dict() for score in permuted],
        "best_test_model": original[0].model,
        "best_bic_model": min(original, key=lambda score: score.train_bic).model,
        "permuted_best_test_model": permuted[0].model,
        "discrimination": discrimination_diagnostics(original, permuted),
    }


def run_benchmark(
    *,
    config: LongitudinalConfig = LongitudinalConfig(),
    measurement: MeasurementConfig = MeasurementConfig(missing_probability=0.10),
) -> dict:
    config.validate()
    results = {
        truth: benchmark_truth(truth, config=config, measurement=measurement)
        for truth in ("receptor", "context", "mixed")
    }
    return {
        "schema_version": 1,
        "warning": (
            "Fully synthetic longitudinal benchmark. Mechanism labels are dimensionless "
            "toy-model covariates, not human exposure recommendations. Proxy sensor "
            "channels are not validated DID biomarkers."
        ),
        "config": asdict(config),
        "measurement": asdict(measurement),
        "model_features": {name: list(features) for name, features in MODEL_FEATURES.items()},
        "results": results,
    }


def _parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--subjects", type=int, default=6)
    p.add_argument("--sessions", type=int, default=24)
    p.add_argument("--micro-population", type=int, default=90)
    p.add_argument("--steps", type=int, default=28)
    p.add_argument("--seed", type=int, default=140)
    p.add_argument("--missing", type=float, default=0.10)
    p.add_argument("--ridge", type=float, default=1e-3)
    p.add_argument("--output", default="runs/dissociation_longitudinal_nulls.json")
    return p


def main() -> int:
    args = _parser().parse_args()
    report = run_benchmark(
        config=LongitudinalConfig(
            subjects=args.subjects,
            sessions=args.sessions,
            micro_population=args.micro_population,
            steps_per_session=args.steps,
            seed=args.seed,
            ridge=args.ridge,
        ),
        measurement=MeasurementConfig(missing_probability=args.missing),
    )
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote longitudinal null-model benchmark to {out}")
    for truth, result in report["results"].items():
        print(
            f"truth={truth:8s} best_test={result['best_test_model']:24s} "
            f"best_bic={result['best_bic_model']:24s} "
            f"after_mechanism_permutation={result['permuted_best_test_model']}"
        )
        diag = result["discrimination"]
        if diag.get("status") == "ok":
            print(
                f"  mechanism_gain_vs_null={diag['mechanism_gain_over_null_fraction']:+.3f} "
                f"permutation_penalty={diag['mechanism_permutation_penalty_fraction']:+.3f}"
            )
        for score in result["scores"][:4]:
            print(
                f"  {score['model']:24s} "
                f"rmse={score['test_rmse']:.4f} "
                f"r2={score['test_r2']:+.3f} "
                f"bic={score['train_bic']:+.1f}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
